version: '3.8'

services:
  web:
    build: .
    container_name: php-app
    ports:
      - "8084:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - sportflexx-net

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: sportflexx
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - sportflexx-net

volumes:
  dbdata:

networks:
  sportflexx-net:

